### ISSUE TITLE
gRPC External Exporter Configuration Options Missing

### ISSUE THREAD

**Issue by natemollica-nm** [hashicorp/consul-telemetry-collector#123]
### Description

While attempting to configure consul-k8s integration to datadog using Datadog's built-in OTLP receiver options for gRPC and HTTP, I found that configuring the gRPC external endpoint outside of the helm value overrides was not possible as it was with the HTTP endpoint.

**Datadog Operator Values**
```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    # Sets: DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT:  0.0.0.0:4317                                                                                                                                              │
    #       DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT:  0.0.0.0:4318
    otlp:
      receiver:
        protocols:
          # Set to "0.0.0.0" as per the below reference docs
          # ref: https://docs.datadoghq.com/opentelemetry/otlp_ingest_in_the_agent/?tab=host#enabling-otlp-ingestion-on-the-datadog-agent
          grpc:
            enabled: true
            endpoint: "0.0.0.0:4317"
```

**Consul Overrides**
```yaml
  metrics:
    enabled: true
    enableAgentMetrics: true
    datadog:
      enabled: true
      otlp:
        enabled: true
        protocol: "grpc"
telemetryCollector:
  enabled: true
```

### Potential Resolution

* Addition of a similar environment variable configuration option to that `CO_OTEL_HTTP_ENDPOINT` for gRPC receivers
* Addition of a similar CLI parameter flag to that of `http-collector-endpoint` for gRPC receivers

### Version

Image: `hashicorp/consul-telemetry-collector:0.0.2`
